- name: put "{{ jenkins_home }}/{{ jenkins_job_name }}-template.yaml"
  template: src=job-template.yaml dest={{ jenkins_home }}/{{ jenkins_job_name }}-template.yaml owner=jenkins group=jenkins backup=yes

- name: create a job
  become: yes
  become_user: jenkins
  shell: "/usr/local/bin/jenkins-jobs update {{ jenkins_home }}/{{ jenkins_job_name }}-template.yaml"
  when: ansible_os_family == "Debian"

- name: create a job
  become: yes
  become_user: jenkins
  shell: "/usr/bin/jenkins-jobs update {{ jenkins_home }}/{{ jenkins_job_name }}-template.yaml"
  when: ansible_os_family == "RedHat"
